# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'performans_rapor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_performans_rapor(object):
    def setupUi(self, performans_rapor):
        performans_rapor.setObjectName("performans_rapor")
        performans_rapor.resize(600, 410)
        performans_rapor.setMinimumSize(QtCore.QSize(600, 410))
        performans_rapor.setMaximumSize(QtCore.QSize(600, 410))
        self.centralwidget = QtWidgets.QWidget(performans_rapor)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 20, 580, 341))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser.setLineWidth(2)
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 360, 131, 23))
        self.pushButton.setStyleSheet("background-color: rgb(0, 173, 181);")
        self.pushButton.setObjectName("pushButton")
        performans_rapor.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(performans_rapor)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        performans_rapor.setStatusBar(self.statusbar)

        self.retranslateUi(performans_rapor)
        self.pushButton.clicked.connect(performans_rapor.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(performans_rapor)

    def retranslateUi(self, performans_rapor):
        _translate = QtCore.QCoreApplication.translate
        performans_rapor.setWindowTitle(_translate("performans_rapor", "Rapor Ekranı"))
        self.pushButton.setText(_translate("performans_rapor", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    performans_rapor = QtWidgets.QMainWindow()
    ui = Ui_performans_rapor()
    ui.setupUi(performans_rapor)
    performans_rapor.show()
    sys.exit(app.exec_())
